### ISSUE TITLE
Zcash Groundbreaker Award

### ISSUE THREAD

**Issue by tromer** [ZcashFoundation/ZcashFoundation#1] opened 2017-03-22 18:09 UTC
I suggest that one of the Foundation's activities will be awarding a "Zcash Groundbreaker Award, in recognition of intellectual giants on whose shoulders Zcash stands".

Rationale:
* We really owe them! Zcash was fortunate to be where things finally came together, but a lot of brilliance and toil brought us here.
* Promoting good will, intellectual honesty and generosity as community values.
* Promoting public awareness for all involved.

The award can consist of:
* online announcements
* an award ceremony (at the Zcash Conference and/or some major pertinent conference)
* a nice plaque
* monetary award in ZEC

Candidates:
* Pioneers of zero-knowledge
* Pioneers of digital payment schemes
* Researchers of modern SNARKs
* Cypherpunk pioneers

**Comment by daira** [comment] 2017-03-23 13:38
In the "Pioneers of digital payment schemes" category, I nominate Tomas Sander and Amnon Ta–Shma.

**Comment by nathan-at-least** [comment] 2017-06-22 20:09
I was just very inspired by some engineering work that has greatly benefited the Zcash reference client development. This is a different focus of award. (-unless you could argue that this is cypherpunk pioneering since cypherpunks write code. ;-)

So perhaps we could have several rewards tracks. In this case I just wanted to award many committers to a repository a relatively small amount without an award ceremony, but perhaps a blog post. If the Foundation sponsored this kind of award, what could we call it?

**Comment by nathan-at-least** [comment] 2017-06-22 20:10
Oh, and I'd like for awards tracks to accept nominations from the public. Not sure how to select actual rewards recipients, though. (Internet voting is fraught with hijinks.)

**Comment by zookozcash** [comment] 2017-06-24 04:20
This is a lovely idea, and reminds me of Max Levchin's wonderful prize:

http://levchinprize.com/
https://www.linkedin.com/pulse/why-i-created-first-prize-real-world-cryptography-max-levchin

I recall that when he announced it, he said he hoped others would chip in to make the size of the prize bigger in the future.

**Comment by jackgavigan** [comment] 2017-06-27 17:23
This strikes me as a "Nobel Prize"-style award. Whilst I agree that it would be a Good Thing, I question whether it falls within the the scope of the Zcash Foundation's [mission](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/MISSION.md).

**Comment by diracdeltas** [comment] 2017-06-27 18:19
I think one of the criteria for the award should be "will use the public recognition and ZEC associated with the award to further the cause of financial privacy and/or for other public good relating to privacy." Otherwise I agree this falls somewhat outside of the foundation's mission.

**Comment by acityinohio** [comment] 2018-09-15 03:59
Closing this as part of ZcF GitHub Issues cleanup.

**Closed as completed by acityinohio** 2018-09-15 03:59 UTC
